image: python:3

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /skip\sci/i
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^dev/
    - if: $CI_COMMIT_MESSAGE =~ /run\sci/i
    # Remove this rule after smedl2 is merged into master, then create a dev*
    # branch for new development
    - if: $CI_COMMIT_BRANCH == "smedl2"

before_script:
  - ping -c 4 stability.cis.upenn.edu
#  - apt-get update -y
#  - apt-get upgrade -y
#  - apt-get install -y libconfig-dev librabbitmq-dev
  - python -V
  - which python

test:
  script:
    - tox
