image: python:3.5

before_script:
  - ping -c 10 stability.cis.upenn.edu
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install -y libconfig-dev librabbitmq-dev
  - python -V
  - which python

test:
  when: manual
  script:
  - pyvenv .env && source .env/bin/activate
  - ls -la .env/bin
  - python -V
  - which python
  - pip install .
  - nosetests -s
