image: python:3.5

before_script:
  - apt-get install -y libconfig9 librabbitmq4
  - python -V
  - which python

test:
  script:
  - pyvenv .env && source .env/bin/activate
  - ls -la .env/bin
  - python -V
  - which python
  - pip install .
  - nosetests
