#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# CAVEAT UTILITOR
# This file was automatically generated by Grako.
#    https://bitbucket.org/apalala/grako/
# Any changes you make to it will be overwritten the
# next time the file is generated.
#

from __future__ import print_function, division, absolute_import, unicode_literals
from grako.parsing import *  # noqa
from grako.exceptions import *  # noqa


__version__ = '14.164.16.49.25'


class RegexpParser(Parser):
    def __init__(self, whitespace=None, **kwargs):
        super(RegexpParser, self).__init__(whitespace=whitespace, **kwargs)

    @rule_def
    def _S0_(self):
        self._S1_()
        self._check_eof()

    @rule_def
    def _S1_(self):

        def block0():
            self._S2_()
        self._closure(block0)

    @rule_def
    def _S2_(self):
        with self._choice():
            with self._option():
                self._S3_()
            with self._option():
                self._S4_()
            self._error('no available options')

    @rule_def
    def _S3_(self):
        self._pattern(r'a')

    @rule_def
    def _S4_(self):
        self._pattern(r'b')


class RegexpSemanticParser(CheckSemanticsMixin, RegexpParser):
    pass


class RegexpSemantics(object):
    def S0(self, ast):
        return ast

    def S1(self, ast):
        return ast

    def S2(self, ast):
        return ast

    def S3(self, ast):
        return ast

    def S4(self, ast):
        return ast


def main(filename, startrule, trace=False, whitespace=None):
    import json
    with open(filename) as f:
        text = f.read()
    parser = RegexpParser(parseinfo=False)
    ast = parser.parse(
        text,
        startrule,
        filename=filename,
        trace=trace,
        whitespace=whitespace)
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(ast, indent=2))
    print()

if __name__ == '__main__':
    import argparse
    import string
    import sys

    class ListRules(argparse.Action):
        def __call__(self, parser, namespace, values, option_string):
            print('Rules:')
            for r in RegexpParser.rule_list():
                print(r)
            print()
            sys.exit(0)

    parser = argparse.ArgumentParser(description="Simple parser for Regexp.")
    parser.add_argument('-l', '--list', action=ListRules, nargs=0,
                        help="list all rules and exit")
    parser.add_argument('-t', '--trace', action='store_true',
                        help="output trace information")
    parser.add_argument('-w', '--whitespace', type=str, default=string.whitespace,
                        help="whitespace specification")
    parser.add_argument('file', metavar="FILE", help="the input file to parse")
    parser.add_argument('startrule', metavar="STARTRULE",
                        help="the start rule for parsing")
    args = parser.parse_args()

    main(args.file, args.startrule, trace=args.trace, whitespace=args.whitespace)