#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by Grako.
#
#    https://pypi.python.org/pypi/grako/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.


from __future__ import print_function, division, absolute_import, unicode_literals

from grako.buffering import Buffer
from grako.parsing import graken, Parser
from grako.util import re, RE_FLAGS, generic_main  # noqa


__version__ = (2016, 8, 29, 15, 33, 41, 0)

__all__ = [
    'pedlParser',
    'pedlSemantics',
    'main'
]

KEYWORDS = set([])


class pedlBuffer(Buffer):
    def __init__(self,
                 text,
                 whitespace=None,
                 nameguard=None,
                 comments_re=None,
                 eol_comments_re=None,
                 ignorecase=None,
                 namechars='',
                 **kwargs):
        super(pedlBuffer, self).__init__(
            text,
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            namechars=namechars,
            **kwargs
        )


class pedlParser(Parser):
    def __init__(self,
                 whitespace=None,
                 nameguard=None,
                 comments_re=None,
                 eol_comments_re=None,
                 ignorecase=None,
                 left_recursion=True,
                 parseinfo=True,
                 keywords=KEYWORDS,
                 namechars='',
                 **kwargs):
        super(pedlParser, self).__init__(
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            left_recursion=left_recursion,
            parseinfo=parseinfo,
            keywords=keywords,
            namechars=namechars,
            **kwargs
        )

    def parse(self, text, *args, **kwargs):
        if not isinstance(text, Buffer):
            text = pedlBuffer(text, **kwargs)
        return super(pedlParser, self).parse(text, *args, **kwargs)

    @graken('Object')
    def _object_(self):
        self._token('object')
        self._identifier_()
        self.name_last_node('object')
        self._token('events')

        def block2():
            self._new_mon_()
        self._positive_closure(block2)
        self.name_last_node('monitors')

        def block4():
            self._event_def_()
        self._positive_closure(block4)
        self.name_last_node('event_defs')
        self._check_eof()
        self.ast._define(
            ['event_defs', 'monitors', 'object'],
            []
        )

    @graken('MonitorConstructor')
    def _new_mon_(self):
        self._token('new')
        self._identifier_()
        self.name_last_node('monitor')
        with self._optional():
            self._token('(')
            self._identifier_list_()
            self.name_last_node('monitor_params')
            self._token(')')
        self._token('=')
        self._token('create')
        self._structure_()
        self.name_last_node('struct')
        self.ast._define(
            ['monitor', 'monitor_params', 'struct'],
            []
        )

    @graken('MonitorStruct')
    def _structure_(self):
        self._identifier_()
        self.name_last_node('struct_id')
        self._token('{')

        def block2():
            self._field_()
        self._closure(block2)
        self.name_last_node('fields')
        self._token('}')
        self.ast._define(
            ['fields', 'struct_id'],
            []
        )

    @graken('Field')
    def _field_(self):
        self._identifier_()
        self.name_last_node('variable')
        self._token('=')
        self._expression_()
        self.name_last_node('value')
        self._token(';')
        self.ast._define(
            ['value', 'variable'],
            []
        )

    @graken('Event')
    def _event_def_(self):
        self._identifier_()
        self.name_last_node('monitor')
        self._token('(')
        self._identifier_list_()
        self.name_last_node('monitor_params')
        self._token(').')
        self._identifier_()
        self.name_last_node('event')
        self._token('(')
        with self._optional():
            self._state_update_list_()
            self.name_last_node('event_params')
        self._token(')')
        self._token('=')
        with self._group():
            with self._choice():
                with self._option():
                    self._token('update(')
                    self._update_param_()
                    self.name_last_node('update_param')
                    self._token(')')
                with self._option():
                    self._token('call(')
                    self._identifier_()
                    self.name_last_node('call_param')
                    self._token(')')
                self._error('no available options')
        with self._optional():
            self._token('when')
            self._expression_()
            self.name_last_node('when')
        self.ast._define(
            ['call_param', 'event', 'event_params', 'monitor', 'monitor_params', 'update_param', 'when'],
            []
        )

    @graken('UpdateParam')
    def _update_param_(self):
        with self._choice():
            with self._option():
                self._identifier_()
                self.name_last_node('update_fn')
                self._token('.')
                self._identifier_()
                self.name_last_node('update_var')
            with self._option():
                self._identifier_()
                self.name_last_node('update_var')
            self._error('no available options')
        self.ast._define(
            ['update_fn', 'update_var'],
            []
        )

    @graken('StateUpdate')
    def _state_update_(self):
        self._target_()
        self.name_last_node('target')
        self._token('=')
        self._expression_()
        self.name_last_node('expression')
        self.ast._define(
            ['expression', 'target'],
            []
        )

    @graken('str')
    def _identifier_(self):
        self._pattern(r'[a-zA-Z][A-Za-z0-9_]*')

    @graken('int')
    def _integer_(self):
        self._pattern(r'[-+]?[0-9]+')

    @graken('float')
    def _float_(self):
        self._pattern(r'[-+]?[0-9]*\.?[0-9]+')

    @graken()
    def _expression_(self):
        with self._choice():
            with self._option():
                self._and_expr_()
                self.name_last_node('or_ex')

                def block1():
                    self._token('||')
                    self._and_expr_()
                    self.name_last_node('or_ex')
                self._positive_closure(block1)
            with self._option():
                self._and_expr_()
                self.name_last_node('@')
            self._error('no available options')
        self.ast._define(
            ['or_ex'],
            []
        )

    @graken()
    def _and_expr_(self):
        with self._choice():
            with self._option():
                self._sub_expr_()
                self.name_last_node('and_ex')

                def block1():
                    self._token('&&')
                    self._sub_expr_()
                    self.name_last_node('and_ex')
                self._positive_closure(block1)
            with self._option():
                self._sub_expr_()
                self.name_last_node('@')
            self._error('no available options')
        self.ast._define(
            ['and_ex'],
            []
        )

    @graken()
    def _sub_expr_(self):
        with self._choice():
            with self._option():

                def block0():
                    self._token('!!')
                self._closure(block0)
                self._token('!(')
                self._expression_()
                self.name_last_node('not_ex')
                self._token(')')
            with self._option():

                def block2():
                    self._token('!!')
                self._closure(block2)
                self._token('(')
                self._expression_()
                self.name_last_node('@')
                self._token(')')
            with self._option():
                self._comp_expr_()
                self.name_last_node('@')
            self._error('no available options')
        self.ast._define(
            ['not_ex'],
            []
        )

    @graken()
    def _comp_expr_(self):
        with self._choice():
            with self._option():
                self._arith_expr_()
                self.name_last_node('comp')

                def block1():
                    with self._group():
                        with self._choice():
                            with self._option():
                                self._token('>=')
                            with self._option():
                                self._token('<=')
                            with self._option():
                                self._token('==')
                            with self._option():
                                self._token('!=')
                            with self._option():
                                self._token('>')
                            with self._option():
                                self._token('<')
                            self._error('expecting one of: != < <= == > >=')
                    self.name_last_node('operator')
                    self._arith_expr_()
                    self.name_last_node('comp')
                self._positive_closure(block1)
            with self._option():
                self._token('(')
                self._comp_expr_()
                self.name_last_node('@')
                self._token(')')
            with self._option():
                self._arith_expr_()
                self.name_last_node('@')
            self._error('no available options')
        self.ast._define(
            ['comp', 'operator'],
            []
        )

    @graken()
    def _arith_expr_(self):
        with self._choice():
            with self._option():
                self._term_()
                self.name_last_node('arith')

                def block1():
                    with self._group():
                        with self._choice():
                            with self._option():
                                self._token('+')
                            with self._option():
                                self._token('-')
                            with self._option():
                                self._token('*')
                            with self._option():
                                self._token('/')
                            with self._option():
                                self._token('%')
                            self._error('expecting one of: % * + - /')
                    self.name_last_node('operator')
                    self._term_()
                    self.name_last_node('arith')
                self._positive_closure(block1)
            with self._option():
                self._term_()
                self.name_last_node('@')
            self._error('no available options')
        self.ast._define(
            ['arith', 'operator'],
            []
        )

    @graken()
    def _term_(self):
        with self._choice():
            with self._option():

                def block0():
                    with self._group():
                        with self._choice():
                            with self._option():
                                self._token('+')
                            with self._option():
                                self._token('-')
                            with self._option():
                                self._token('~')
                            with self._option():
                                self._token('!')
                            self._error('expecting one of: ! + - ~')
                    self.name_last_node('unary')
                self._closure(block0)
                self._atom_()
                self.name_last_node('atom')

                def block4():
                    self._trailer_()
                    self.name_last_node('trailer')
                self._closure(block4)
            with self._option():

                def block6():
                    with self._group():
                        with self._choice():
                            with self._option():
                                self._token('+')
                            with self._option():
                                self._token('-')
                            with self._option():
                                self._token('~')
                            self._error('expecting one of: + - ~')
                    self.name_last_node('unary')
                self._closure(block6)
                self._token('(')
                self._arith_expr_()
                self.name_last_node('@')
                self._token(')')
            self._error('no available options')
        self.ast._define(
            ['atom', 'trailer', 'unary'],
            []
        )

    @graken()
    def _atom_(self):
        with self._choice():
            with self._option():
                self._integer_()
            with self._option():
                self._float_()
            with self._option():
                self._identifier_()
            with self._option():
                self._token('true')
            with self._option():
                self._token('false')
            with self._option():
                self._token('null')
            self._error('expecting one of: false null true')

    @graken()
    def _trailer_(self):
        with self._choice():
            with self._option():
                self._token('[')
                with self._optional():
                    self._expression_()
                    self.name_last_node('index')
                self._token(']')
            with self._option():
                self._token('(')
                with self._optional():
                    self._expression_list_()
                    self.name_last_node('params')
                self._token(')')
            with self._option():
                self._token('.')
                self._identifier_()
                self.name_last_node('dot')

                def block3():
                    self._trailer_()
                    self.name_last_node('trailer')
                self._closure(block3)
            self._error('expecting one of: ( [')
        self.ast._define(
            ['dot', 'index', 'params', 'trailer'],
            []
        )

    @graken()
    def _target_(self):
        self._identifier_()

    @graken()
    def _expression_list_(self):
        with self._choice():
            with self._option():
                self._expression_()
                self.name_last_node('@')

                def block1():
                    self._token(',')
                    self._expression_()
                    self.name_last_node('@')
                self._closure(block1)
            with self._option():
                pass
            self._error('no available options')

    @graken()
    def _identifier_list_(self):
        with self._choice():
            with self._option():
                self._identifier_()
                self.name_last_node('@')

                def block1():
                    self._token(',')
                    self._identifier_()
                    self.name_last_node('@')
                self._closure(block1)
            with self._option():
                pass
            self._error('no available options')

    @graken()
    def _state_update_list_(self):
        with self._choice():
            with self._option():
                self._state_update_()
                self.name_last_node('@')

                def block1():
                    self._token(',')
                    self._state_update_()
                    self.name_last_node('@')
                self._closure(block1)
            with self._option():
                pass
            self._error('no available options')


class pedlSemantics(object):
    def object(self, ast):
        return ast

    def new_mon(self, ast):
        return ast

    def structure(self, ast):
        return ast

    def field(self, ast):
        return ast

    def event_def(self, ast):
        return ast

    def update_param(self, ast):
        return ast

    def state_update(self, ast):
        return ast

    def identifier(self, ast):
        return ast

    def integer(self, ast):
        return ast

    def float(self, ast):
        return ast

    def expression(self, ast):
        return ast

    def and_expr(self, ast):
        return ast

    def sub_expr(self, ast):
        return ast

    def comp_expr(self, ast):
        return ast

    def arith_expr(self, ast):
        return ast

    def term(self, ast):
        return ast

    def atom(self, ast):
        return ast

    def trailer(self, ast):
        return ast

    def target(self, ast):
        return ast

    def expression_list(self, ast):
        return ast

    def identifier_list(self, ast):
        return ast

    def state_update_list(self, ast):
        return ast


def main(
        filename,
        startrule,
        trace=False,
        whitespace=None,
        nameguard=None,
        comments_re=None,
        eol_comments_re=None,
        ignorecase=None,
        left_recursion=True,
        parseinfo=True,
        **kwargs):

    with open(filename) as f:
        text = f.read()
    whitespace = whitespace or None
    parser = pedlParser(parseinfo=False)
    ast = parser.parse(
        text,
        startrule,
        filename=filename,
        trace=trace,
        whitespace=whitespace,
        nameguard=nameguard,
        ignorecase=ignorecase,
        **kwargs)
    return ast

if __name__ == '__main__':
    import json
    ast = generic_main(main, pedlParser, name='pedl')
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(ast, indent=2))
    print()
