# GitHub Actions workflow for manually regenerating the docs and publishing to
# GitHub Pages
# vim: set ts=8 sts=2 sw=2:
name: Regenerate Docs
on: workflow_dispatch

jobs:
  regen-docs:
    name: Regenerate and publish docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #- name: Install Python packaging tools
      #  run: python3 -m pip install --upgrade pip setuptools wheel
      - name: Install Sphinx
        run: python3 -m pip install --upgrade sphinx
      - name: Build Sphinx docs
        run: |
          cd docs
          make html
      - name: Publish Sphinx docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
